/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Messages
{
  public enum Modification
  {
    NONE = 0,
    ADDED = 1,
    UPDATED = 2,
    DELETED = 3,
  }
}
